export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_EMAIL = 'SET_EMAIL';

export const SET_FLOW_DATA = 'SET_FLOW_DATA';

//Demand
export const SET_DEMAND_VISIBILITY = 'SET_DEMAND_VISIBILITY';
export const SET_FILTER_DEMAND = 'SET_FILTER_DEMAND';

//Label
export const SET_LABEL_VISIBILITY = "SET_LABEL_VISIBILITY"

//Inflow
export const SET_INFLOW_VISIBILITY = 'SET_INFLOW_VISIBILITY';
export const SET_FILTER_INFLOW = 'SET_FILTER_INFLOW';

//Amenities
export const SET_AMENITY_VISIBILITY = 'SET_AMENITY_VISIBILITY';
export const SET_FILTER_AMENITY = 'SET_FILTER_AMENITY';

//Irrigation
export const SET_IRRIGATION_VISIBILITY = 'SET_IRRIGATION_VISIBILITY';
export const SET_FILTER_IRRIGATION = 'SET_FILTER_IRRIGATION';

//Non-Irrigation
export const SET_NONIRRIGATION_VISIBILITY = 'SET_NONIRRIGATION_VISIBILITY';
export const SET_FILTER_NONIRRIGATION = 'SET_FILTER_NONIRRIGATION';

export const SET_MODE = 'SET_MODE';

export const SET_USER = 'SET_USER';

